# Generated by Django 5.1.3 on 2024-12-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_options_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Image representing the category.', null=True, upload_to='categories/'),
        ),
    ]
