# Generated by Django 5.1.3 on 2024-12-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default_image.jpeg', upload_to='products/'),
        ),
    ]
